export type ComparisonSymbols = '==';
export type resultTypes = 'SUCCESS' | 'INVALID_PASSWORD' | 'INVALID_FORM' | 'NON_FOUND_USER' | 'UNKNOWN_ERROR' | 'USER_ALREADY_REGISTERED' | 'USER_SUCCESSFULLY_REGISTERED';
